# -*- coding: utf-8 -*-
"""conexiónMYSQL-Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VHErrcdjv2QCbZxF4u7JbXbj-Dsc7FTx

# Conexión MYSQL con Python

**1) Instalar pymysql para poder conectarnos desde Python**
"""

pip install pymysql

"""**2) Conexión a la BBDD**"""

import pymysql
try:
	conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             db='')
	print("Conexión correcta")
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
	print("Ocurrió un error al conectar: ", e)

"""**A modo de ejemplo usaremos la base de datos "películas"**

---

**3) Consulta de base de datos**
"""

import pymysql
try:
	conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             db='peliculas')
	try:
		with conexion.cursor() as cursor:
			# En este caso no necesitamos limpiar ningún dato
			cursor.execute("SELECT id, titulo, anio FROM peliculas;")

			# Con fetchall traemos todas las filas
			peliculas = cursor.fetchall()

			# Recorrer e imprimir
			for pelicula in peliculas:
				print(pelicula)
	finally:
		conexion.close()
	
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
	print("Ocurrió un error al conectar: ", e)

"""**4) Consulta con sentencia WHERE**"""

import pymysql
try:
	conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             db='peliculas')
	try:
		with conexion.cursor() as cursor:
			
			consulta = "SELECT id, titulo, anio FROM peliculas WHERE anio > %s;"
			cursor.execute(consulta, (2000))

			# Con fetchall traemos todas las filas
			peliculas = cursor.fetchall()

			# Recorrer e imprimir
			for pelicula in peliculas:
				print(pelicula)
	finally:
		conexion.close()
	
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
	print("Ocurrió un error al conectar: ", e)

"""**5) Editar**"""

import pymysql
try:
	conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             db='peliculas')
	try:
		with conexion.cursor() as cursor:
			
			consulta = "UPDATE peliculas SET titulo = %s WHERE id = %s;"
			nuevo_titulo = "Ready Player One: comienza el juego"
			id_editar = 2
			cursor.execute(consulta, (nuevo_titulo, id_editar))

		# No olvidemos hacer commit cuando hacemos un cambio a la BD
		conexion.commit()
	finally:
		conexion.close()
	
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
	print("Ocurrió un error al conectar: ", e)

"""**6) Eliminar**"""

import pymysql
try:
	conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             db='peliculas')
	try:
		with conexion.cursor() as cursor:
			
			consulta = "DELETE FROM peliculas WHERE anio < %s;"
			anio = 2000
			cursor.execute(consulta, (anio))

		# No olvidemos hacer commit cuando hacemos un cambio a la BD
		conexion.commit()
	finally:
		conexion.close()
	
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
	print("Ocurrió un error al conectar: ", e)

"""**7) Insertar**"""

import pymysql
try:
	conexion = pymysql.connect(host='localhost',
                             user='root',
                             password='',
                             db='peliculas')
	try:
		with conexion.cursor() as cursor:
			consulta = "INSERT INTO peliculas(titulo, anio) VALUES (%s, %s);"
			#Podemos llamar muchas veces a .execute con datos distintos
			cursor.execute(consulta, ("Volver al futuro 1", 1985))
			cursor.execute(consulta, ("Ready Player One", 2018))
			cursor.execute(consulta, ("It", 2017))
			cursor.execute(consulta, ("Pulp Fiction", 1994))
		conexion.commit()
	finally:
		conexion.close()
except (pymysql.err.OperationalError, pymysql.err.InternalError) as e:
	print("Ocurrió un error al conectar: ", e)